# Generated by Django 3.2.6 on 2021-08-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='paid_until',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='subscription_plan',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('half_year', 'Half Year'), ('yearly', 'Yearly')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='subscription_type',
            field=models.CharField(choices=[('free', 'Free'), ('paid', 'Paid')], default='free', max_length=12),
        ),
    ]
