# Generated by Django 3.2.6 on 2021-09-04 07:35

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_game_support_game'),
        ('operator', '0002_auto_20210819_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('name', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=64)),
                ('default_language', models.CharField(max_length=2)),
                ('default_currency', models.CharField(max_length=3)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='operator',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='operator',
            name='paid_until',
        ),
        migrations.RemoveField(
            model_name='operator',
            name='subscription_plan',
        ),
        migrations.RemoveField(
            model_name='operator',
            name='subscription_type',
        ),
        migrations.RemoveField(
            model_name='operatorconfiguration',
            name='general_styling',
        ),
        migrations.AddField(
            model_name='operator',
            name='is_access_premium_games',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='operator',
            name='supported_games',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.game'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='schema',
            field=models.SlugField(unique=True),
        ),
        migrations.CreateModel(
            name='OperatorWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('home_page_video', models.URLField()),
                ('about_us_title', models.TextField()),
                ('about_us_description', ckeditor.fields.RichTextField()),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operator.operator')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OperatorHomeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sections/')),
                ('title', models.CharField(max_length=256)),
                ('description', ckeditor.fields.RichTextField()),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operator.operator')),
            ],
        ),
        migrations.CreateModel(
            name='OperatorFaq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', ckeditor.fields.RichTextField()),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operator.operator')),
            ],
        ),
        migrations.AddField(
            model_name='operator',
            name='country',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='operator.country'),
        ),
    ]
