# Generated by Django 3.2.6 on 2021-09-04 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_game_support_game'),
        ('operator', '0003_auto_20210904_0735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operator',
            name='supported_games',
        ),
        migrations.AddField(
            model_name='operator',
            name='supported_games',
            field=models.ManyToManyField(to='core.Game'),
        ),
    ]
