# Generated by Django 3.2.6 on 2021-09-11 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operator', '0004_auto_20210904_0746'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Country',
            new_name='Region',
        ),
        migrations.RenameField(
            model_name='operator',
            old_name='country',
            new_name='region',
        ),
    ]
