# Generated by Django 3.2.6 on 2021-09-11 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operator', '0005_auto_20210911_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatorhomesection',
            name='summary',
            field=models.TextField(null=True),
        ),
    ]
