# Generated by Django 3.2.6 on 2021-09-11 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operator', '0006_operatorhomesection_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('event_type', models.CharField(choices=[('event', 'Event'), ('affiliate', 'Affiliate'), ('replay', 'Replay')], max_length=16)),
                ('image', models.ImageField(upload_to='events/')),
                ('title', models.CharField(blank=True, max_length=64, null=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operator.operator')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
