# Generated by Django 3.2.6 on 2021-09-13 04:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operator', '0009_alter_operator_is_access_premium_games'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operatorwebsite',
            name='about_us_title',
        ),
        migrations.AddField(
            model_name='operatorwebsite',
            name='conditions_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operatorwebsite',
            name='terms_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
