# Generated by Django 3.2.6 on 2021-09-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operator', '0010_auto_20210913_0436'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('name', models.CharField(max_length=64)),
                ('ad_file', models.FileField(upload_to='ads/')),
                ('ad_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=32)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Ad',
                'verbose_name_plural': 'Ads',
            },
        ),
    ]
