# Generated by Django 3.2.6 on 2021-09-16 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operator', '0012_auto_20210915_1952'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OperatorEvent',
        ),
    ]
