# Generated by Django 3.2.7 on 2021-10-06 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operator', '0014_operatorhomesection_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operatorhomesection',
            name='description',
        ),
        migrations.AddField(
            model_name='operatorhomesection',
            name='background_image',
            field=models.ImageField(null=True, upload_to='sections/background/'),
        ),
        migrations.AddField(
            model_name='operatorhomesection',
            name='image_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operatorhomesection',
            name='image',
            field=models.ImageField(upload_to='sections/', verbose_name='Main Image'),
        ),
    ]
