# Generated by Django 3.2.7 on 2021-11-18 22:32

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operator', '0016_remove_operatorhomesection_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operatorwebsite',
            name='conditions_description',
        ),
        migrations.AlterField(
            model_name='operatorhomesection',
            name='image_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='operatorwebsite',
            name='about_us_description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='operatorwebsite',
            name='terms_description',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Terms & Conditions'),
        ),
    ]
