# Generated by Django 3.2.7 on 2021-11-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operator', '0019_auto_20211122_1903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='redeempackage',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='redeempackage',
            name='coins',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
