# Generated by Django 3.2.7 on 2021-12-02 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operator', '0020_auto_20211127_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operatorad',
            name='operators',
        ),
        migrations.AddField(
            model_name='operatorad',
            name='regions',
            field=models.ManyToManyField(to='operator.Region'),
        ),
    ]
