# Generated by Django 3.1.1 on 2022-01-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operator', '0022_auto_20220110_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='default_currency',
            field=models.CharField(choices=[('₦', 'Naira'), ('$', 'USD')], default='₦', max_length=3),
        ),
    ]
