# Generated by Django 3.1.1 on 2022-01-19 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operator', '0023_auto_20220118_1613'),
        ('operator', '0023_auto_20220112_0900'),
    ]

    operations = [
    ]
