# Generated by Django 3.1.1 on 2022-02-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operator', '0025_auto_20220119_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatorhomesection',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='sections/background/'),
        ),
        migrations.AlterField(
            model_name='operatorhomesection',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operatorhomesection',
            name='title',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
