# Generated by Django 3.1.1 on 2022-04-11 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operator', '0026_auto_20220222_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatorhomesection',
            name='button_label',
            field=models.TextField(blank=True, null=True),
        ),
    ]
