# Generated by Django 3.1.1 on 2022-04-12 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operator', '0027_operatorhomesection_button_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatorhomesection',
            name='button_label',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
