# Generated by Django 3.1.1 on 2022-04-19 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operator', '0028_auto_20220412_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatorwebsite',
            name='second_section_image',
            field=models.ImageField(null=True, upload_to='home_page_image/', verbose_name='Second section image (mobile)'),
        ),
        migrations.AlterField(
            model_name='operatorwebsite',
            name='first_section_image',
            field=models.ImageField(null=True, upload_to='home_page_image/', verbose_name='First section image (desktop)'),
        ),
    ]
