# Generated by Django 3.1.1 on 2022-05-05 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operator', '0029_auto_20220419_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatorad',
            name='ad_file_mobile',
            field=models.FileField(blank=True, null=True, upload_to='ads/', verbose_name='Mobile Ad file'),
        ),
        migrations.AlterField(
            model_name='operatorad',
            name='ad_file',
            field=models.FileField(upload_to='ads/', verbose_name='Dektop Ad file'),
        ),
    ]
