# Generated by Django 3.1.1 on 2022-05-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operator', '0030_auto_20220505_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatorad',
            name='ad_file_mobile',
            field=models.FileField(upload_to='ads/', verbose_name='Mobile Ad file'),
        ),
    ]
