# Generated by Django 3.2.6 on 2021-08-19 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_paid_until'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='paid_until',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscription_plan',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscription_type',
        ),
    ]
