# Generated by Django 3.2.6 on 2021-08-24 10:42

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210819_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(null=True),
        ),
    ]
