# Generated by Django 3.2.6 on 2021-09-11 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('action', models.CharField(choices=[('add', 'Add'), ('redeem', 'Redeem')], max_length=12)),
                ('amount', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Redeem History',
                'verbose_name_plural': 'Redeem History',
            },
        ),
        migrations.DeleteModel(
            name='UserRedeemHistory',
        ),
    ]
