# Generated by Django 3.2.6 on 2021-09-13 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_sticker_trophy'),
        ('account', '0009_user_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stickers',
            field=models.ManyToManyField(to='core.Sticker'),
        ),
        migrations.AddField(
            model_name='user',
            name='trophies',
            field=models.ManyToManyField(to='core.Trophy'),
        ),
    ]
