# Generated by Django 3.2.7 on 2021-09-26 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_usergameplayed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='app_fcm_token',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='web_fcm_token',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
