# Generated by Django 3.2.7 on 2021-09-28 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20210928_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='type',
            field=models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile')], default='web', max_length=8),
        ),
    ]
