# Generated by Django 3.2.7 on 2021-09-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_usernotification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='last_read',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
