# Generated by Django 3.2.7 on 2021-09-29 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_notifications'),
        ('account', '0017_alter_usernotification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='notification',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.notifications'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='usernotification',
            unique_together={('user', 'notification')},
        ),
        migrations.RemoveField(
            model_name='usernotification',
            name='action',
        ),
        migrations.RemoveField(
            model_name='usernotification',
            name='template',
        ),
        migrations.RemoveField(
            model_name='usernotification',
            name='text',
        ),
        migrations.RemoveField(
            model_name='usernotification',
            name='title',
        ),
        migrations.RemoveField(
            model_name='usernotification',
            name='type',
        ),
        migrations.RemoveField(
            model_name='usernotification',
            name='url',
        ),
    ]
