# Generated by Django 3.2.7 on 2021-10-01 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_mission_action'),
        ('account', '0021_user_uid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendlist',
            options={'verbose_name_plural': 'Friends List'},
        ),
        migrations.AlterField(
            model_name='user',
            name='stickers',
            field=models.ManyToManyField(blank=True, to='core.Sticker'),
        ),
        migrations.AlterField(
            model_name='user',
            name='trophies',
            field=models.ManyToManyField(null=True, to='core.Trophy'),
        ),
    ]
