# Generated by Django 3.2.7 on 2021-10-01 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_mission_action'),
        ('account', '0022_auto_20211001_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='trophies',
            field=models.ManyToManyField(blank=True, to='core.Trophy'),
        ),
    ]
