# Generated by Django 3.2.7 on 2021-10-11 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20211011_1119'),
        ('account', '0027_alter_usernotification_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBattlePass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('activity_coins', models.PositiveIntegerField(verbose_name=0)),
                ('battlepass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.battlepass')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
