# Generated by Django 3.2.7 on 2021-10-15 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0029_auto_20211011_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergameplayed',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
