# Generated by Django 3.2.7 on 2021-10-18 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_alter_usergameplayed_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usergameplayed',
            name='last_played_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
