# Generated by Django 3.2.7 on 2021-10-19 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0031_auto_20211018_0627'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription',
            field=models.CharField(choices=[('free', 'Free'), ('paid', 'Paid')], default='free', max_length=50),
        ),
    ]
