# Generated by Django 3.2.7 on 2021-10-20 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0032_user_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendlist',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('declined', 'Declined'), ('pending', 'Pending')], default='pending', max_length=16),
        ),
    ]
