# Generated by Django 3.2.7 on 2021-11-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0037_auto_20211030_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscription',
            field=models.CharField(choices=[('free', 'Free'), ('paid1', 'Paid 1'), ('paid2', 'Paid 2')], default='free', max_length=50),
        ),
    ]
