# Generated by Django 3.2.7 on 2021-11-22 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_alter_html5game_game_type'),
        ('account', '0039_alter_usernotification_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBattlePass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('is_vip', models.BooleanField(default=False)),
                ('vip_date', models.DateTimeField(blank=True, null=True)),
                ('battlepass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.battlepass')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
