# Generated by Django 3.2.7 on 2021-11-30 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_auto_20211130_1529'),
        ('account', '0040_userbattlepass'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userbattlepass',
            unique_together={('user', 'battlepass')},
        ),
    ]
