# Generated by Django 3.2.7 on 2021-12-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0041_alter_userbattlepass_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_profile_open_at',
            field=models.DateTimeField(null=True),
        ),
    ]
