# Generated by Django 3.2.7 on 2021-12-04 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0042_user_last_profile_open_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_profile_open_at',
        ),
    ]
