# Generated by Django 3.2.7 on 2021-12-08 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operator', '0021_auto_20211202_2353'),
        ('account', '0044_alter_user_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='operator.region'),
        ),
    ]
