# Generated by Django 3.2.7 on 2021-12-29 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0048_auto_20211229_1727'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertransactionhistory',
            options={'verbose_name': 'Coins History', 'verbose_name_plural': 'Coins History'},
        ),
        migrations.AlterField(
            model_name='usertransactionhistory',
            name='action',
            field=models.CharField(choices=[('add', 'Add'), ('send', 'Send'), ('receive', 'Receive'), ('redeem', 'Redeem')], default='add', max_length=12),
        ),
        migrations.AlterField(
            model_name='usertransactionhistory',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
