# Generated by Django 3.1.1 on 2022-01-19 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0052_auto_20220112_0900'),
        ('account', '0053_user_last_seen'),
    ]

    operations = [
    ]
