# Generated by Django 3.1.1 on 2022-01-19 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0056_user_last_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_seen',
        ),
    ]
