# Generated by Django 3.1.1 on 2022-01-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0058_user_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
