# Generated by Django 3.1.1 on 2022-02-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0059_usernotification_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertransactionhistory',
            name='action',
            field=models.CharField(choices=[('add', 'Add'), ('buy', 'Buy'), ('send', 'Send'), ('receive', 'Receive'), ('redeem', 'Redeem'), ('pay', 'Pay Fee')], default='add', max_length=12),
        ),
    ]
