# Generated by Django 3.1.1 on 2022-03-06 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_auto_20220306_2144'),
        ('tournament', '0033_auto_20220301_1514'),
        ('account', '0060_auto_20220206_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergamelinkedaccount',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tournament.tournament'),
        ),
        migrations.AlterUniqueTogether(
            name='usergamelinkedaccount',
            unique_together={('user', 'game', 'tournament')},
        ),
    ]
