# Generated by Django 3.1.1 on 2022-03-06 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0061_auto_20220306_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='game_nicknames',
            field=models.ManyToManyField(related_name='_user_game_nicknames_+', to='account.UserGameLinkedAccount'),
        ),
    ]
