# Generated by Django 3.1.1 on 2022-03-08 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0064_user_game_nicknames'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='game_nicknames',
            field=models.ManyToManyField(blank=True, related_name='_user_game_nicknames_+', to='account.UserGameLinkedAccount'),
        ),
        migrations.DeleteModel(
            name='UserGameNicknames',
        ),
    ]
