# Generated by Django 3.1.1 on 2022-03-08 18:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0033_auto_20220301_1514'),
        ('account', '0065_auto_20220308_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergamelinkedaccount',
            name='tournament',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='tournament.tournament'),
            preserve_default=False,
        ),
    ]
