# Generated by Django 3.1.1 on 2022-03-08 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0066_auto_20220308_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='game_nicknames',
        ),
    ]
