# Generated by Django 3.1.1 on 2022-03-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0067_remove_user_game_nicknames'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='is_popup',
            field=models.BooleanField(default=False),
        ),
    ]
