# Generated by Django 3.1.1 on 2022-05-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0070_usersectionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='old_coins',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='seen_coins',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usertransactionhistory',
            name='info',
            field=models.CharField(blank=True, choices=[('add', 'Add'), ('buy', 'Buy'), ('send', 'Send'), ('receive', 'Receive'), ('redeem', 'Redeem'), ('pay', 'Pay Fee')], max_length=50, null=True),
        ),
    ]
