# Generated by Django 3.2.6 on 2021-08-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameapi',
            name='api_key',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='gameapi',
            name='check_match_threshold',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='gameapi',
            name='create_match',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='gameapi',
            name='create_tournament',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
