# Generated by Django 3.2.6 on 2021-08-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210819_1534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameapi',
            options={'verbose_name': 'API', 'verbose_name_plural': 'APIs'},
        ),
        migrations.RemoveField(
            model_name='gameapi',
            name='base_url',
        ),
        migrations.AddField(
            model_name='gameapi',
            name='headers',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='gameapi',
            name='check_match_threshold',
            field=models.IntegerField(default=60, help_text='in seconds'),
        ),
    ]
