# Generated by Django 3.2.6 on 2021-08-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210824_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameapi',
            name='response_mapping',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gameapi',
            name='create_match',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='gameapi',
            name='create_tournament',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='gameapi',
            name='fetch_match_info',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='gameapi',
            name='fetch_player_info',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='gameapi',
            name='fetch_tournament_info',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
