# Generated by Django 3.2.6 on 2021-08-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210824_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameapi',
            name='headers',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
