# Generated by Django 3.2.6 on 2021-08-27 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_gameapi_headers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameapi',
            name='api_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
