# Generated by Django 3.2.6 on 2021-09-15 19:52

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operator', '0012_auto_20210915_1952'),
        ('core', '0011_sticker_trophy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trophy',
            options={'verbose_name_plural': 'Trophies'},
        ),
        migrations.AlterField(
            model_name='trophy',
            name='image',
            field=models.ImageField(upload_to='trophies/'),
        ),
        migrations.CreateModel(
            name='HTML5Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('name', models.CharField(max_length=256)),
                ('slug', models.SlugField()),
                ('image', models.ImageField(upload_to='html5_games/')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('url', models.URLField()),
                ('supported_operators', models.ManyToManyField(to='operator.Operator')),
            ],
            options={
                'verbose_name': 'HTML5 Game',
                'verbose_name_plural': 'HTML5 Games',
            },
        ),
    ]
