# Generated by Django 3.2.6 on 2021-09-16 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210915_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('event_type', models.CharField(choices=[('show', 'SHOWS'), ('affiliate', 'AFFILIATES'), ('event', 'EVENTS')], max_length=16)),
                ('image', models.ImageField(upload_to='events/')),
                ('title', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
