# Generated by Django 3.2.6 on 2021-09-22 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_html5game_game_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BattlePass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('name', models.CharField(max_length=128)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('max_level', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BattlePassLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField()),
                ('free_video', models.PositiveIntegerField(blank=True, null=True)),
                ('free_coins', models.PositiveIntegerField(blank=True, null=True)),
                ('free_data', models.PositiveIntegerField(blank=True, null=True)),
                ('battle_pass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.battlepass')),
            ],
        ),
        migrations.CreateModel(
            name='CoinPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField()),
                ('coins', models.PositiveIntegerField()),
                ('bonus', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('name', models.CharField(max_length=512)),
                ('action', models.CharField(choices=[('sign_up', 'On Sign Up'), ('ad_watch', 'On Ad Watch'), ('win_match', 'On Match Win'), ('win_tournament', 'On Tournament Win')], max_length=64, unique=True)),
                ('coins', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='profile-images/')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.configuration')),
            ],
        ),
        migrations.CreateModel(
            name='RedeemPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('image', models.ImageField(upload_to='packages/')),
                ('coins', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='ActionCoin',
        ),
        migrations.RemoveField(
            model_name='html5game',
            name='name',
        ),
        migrations.AddField(
            model_name='html5game',
            name='game',
            field=models.CharField(choices=[('mad_shark', 'Mad Shark')], default='mad_shark', max_length=256, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='html5game',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
