# Generated by Django 3.2.6 on 2021-09-23 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210922_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='support_game',
            field=models.CharField(choices=[('dota2', 'Dota 2'), ('clash_royal', 'Clash Royal'), ('pubg', 'PUGB'), ('cod', 'Call Of Duty'), ('fifa', 'Fifa')], max_length=32, null=True),
        ),
    ]
