# Generated by Django 3.2.7 on 2021-09-29 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20210929_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='html5game',
            name='game',
            field=models.CharField(choices=[('mad_shark', 'Mad Shark')], max_length=256),
        ),
        migrations.AlterField(
            model_name='html5game',
            name='slug',
            field=models.SlugField(),
        ),
    ]
