# Generated by Django 3.2.7 on 2021-09-29 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20210929_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='gifted_coins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notifications',
            name='is_gift',
            field=models.BooleanField(default=False),
        ),
    ]
