# Generated by Django 3.2.7 on 2021-09-29 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_notifications_is_claimed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='gifted_coins',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
