# Generated by Django 3.2.7 on 2021-09-29 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_notifications_gifted_coins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='is_claimed',
        ),
    ]
