# Generated by Django 3.2.7 on 2021-09-30 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_notifications_is_claimed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='action',
            field=models.CharField(choices=[('play_game', 'Play one game'), ('join_tournament', 'Participate in a tournament'), ('watch_video', 'Watch a video'), ('invite_friend', 'Invite a friend to Engage'), ('challenge_friend', 'Challenge a friend to any game'), ('play_with_friend', 'Play any game with a friend'), ('watch_2_videos', 'Watch two videos'), ('play_2_games', 'Play any two games'), ('win_tournament', 'Win a tournament')], max_length=64, unique=True),
        ),
    ]
