# Generated by Django 3.2.7 on 2021-10-07 03:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20211006_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='template',
            field=models.CharField(choices=[('home', 'Home Dashboard'), ('login', 'After Login'), ('christmas', 'Christmas'), ('easter', 'Easter'), ('instant', 'Instant'), ('how_to_use', 'How To Use Engage')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos_uploaded/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm'])]),
        ),
    ]
