# Generated by Django 3.2.7 on 2021-10-11 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_notifications_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='template',
            field=models.CharField(choices=[('home', 'When User Reach Home Dashboard'), ('login', 'After User Login'), ('instant', 'Instant'), ('how_to_use', 'How To Use Engage'), ('active_5_days', '5 Active Days After Joining'), ('active_10_days', '10 Active Days After Joining'), ('active_30_days', '30 Active Days After Joining'), ('user_register_for_tournament', 'User Registers For Tournament'), ('user_first_tournament', 'User Who Is First In Any Tournament'), ('user_second_third_tournament', 'Users Who Are Second, Third'), ('user_outside_the_winning_positions', 'User Outside The Winning Positions'), ('happy_birthday', 'Happy Birthday'), ('friend_added', 'Friend Added'), ('friend_remove', 'Friend Remove'), ('friend_request', 'Friend Request'), ('once_a_month', 'once_a_month'), ('daily', 'Daily')], max_length=40, null=True),
        ),
    ]
