# Generated by Django 3.2.7 on 2021-10-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20211011_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='battlepass',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
