# Generated by Django 3.2.7 on 2021-10-11 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_battlepass_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battlepass',
            name='ends_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='battlepass',
            name='starts_at',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='BattlePassMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('battle_pass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.battlepass')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mission')),
            ],
            options={
                'unique_together': {('battle_pass', 'mission', 'date')},
            },
        ),
    ]
