# Generated by Django 3.2.7 on 2021-10-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20211011_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='battlepass',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='battlepass/'),
        ),
    ]
