# Generated by Django 3.2.7 on 2021-10-23 11:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_remove_html5game_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('logo', models.ImageField(upload_to='games/icons/')),
                ('name', models.CharField(max_length=256)),
                ('pc_url', models.CharField(blank=True, max_length=512, null=True)),
                ('mobile_url', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='game',
            name='is_featured',
        ),
        migrations.AddField(
            model_name='coinpurchase',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coinpurchase',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified Date'),
        ),
    ]
