# Generated by Django 3.2.7 on 2021-10-31 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_auto_20211023_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='go_link',
            field=models.URLField(null=True, verbose_name='GO Link'),
        ),
    ]
