# Generated by Django 3.2.7 on 2021-11-08 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_auto_20211105_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredgame',
            name='android_link',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='featuredgame',
            name='ios_link',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='featuredgame',
            name='pc_link',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
