# Generated by Django 3.2.7 on 2021-11-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_auto_20211108_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_max_length',
            field=models.PositiveIntegerField(help_text='per minute', null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='game_model',
            field=models.CharField(choices=[('top_scorer', 'Top Scorer'), ('battle_royale', 'Battle Royale'), ('team_based', 'Team-Based')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='has_api',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='room_size',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='android_link',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='ios_link',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='pc_link',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
