# Generated by Django 3.2.7 on 2021-11-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_alter_notifications_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='support_game',
            field=models.CharField(choices=[('dota2', 'Dota 2'), ('clash_royale', 'Clash Royale'), ('pubg', 'PUGB'), ('cod', 'Call Of Duty'), ('fifa', 'Fifa')], max_length=32, null=True, verbose_name='Supported Game'),
        ),
    ]
