# Generated by Django 3.2.7 on 2021-11-22 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_alter_html5game_game_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoinPurchase',
        ),
        migrations.DeleteModel(
            name='RedeemPackage',
        ),
    ]
