# Generated by Django 3.2.7 on 2021-11-24 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operator', '0019_auto_20211122_1903'),
        ('core', '0055_auto_20211122_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='regions',
            field=models.ManyToManyField(to='operator.Region'),
        ),
    ]
