# Generated by Django 3.2.7 on 2021-11-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_auto_20211130_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified Date'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
    ]
