# Generated by Django 3.2.7 on 2021-12-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_auto_20211130_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='battlepass',
            name='unlock_vip_cost',
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True),
        ),
    ]
