# Generated by Django 3.2.7 on 2021-12-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_auto_20211202_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='html5game',
            name='game',
            field=models.CharField(choices=[('adventure_quiz', 'Adventure Quiz'), ('angry_zombies', 'Angry Zombies'), ('alien_vs_math', 'Alien vs Math'), ('animals_memory', 'Animals Memory'), ('cannon_ball', 'Cannon Ball'), ('cat_jump', 'Cat Jump'), ('cat_vs_dog', 'Cat Vs Dog'), ('conquer_your_love', 'Conquer your love'), ('galaxy_domination', 'Galaxy Domination'), ('mad_shark', 'Mad Shark'), ('memory_animal_game', 'Memory Animal Game'), ('prehistoric_warfare', 'Prehistoric Warfare'), ('slice_fruit', 'Slice Fruit'), ('soccer_heroes', 'Soccer Heroes'), ('spot_the_difference', 'Spot the Difference'), ('super_quiz_xml', 'Super Quiz XML'), ('sweet_memory', 'Sweet Memory')], max_length=256),
        ),
    ]
