# Generated by Django 3.2.7 on 2021-12-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_alter_html5game_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='action',
            field=models.CharField(choices=[('popup_image', 'Popup Image'), ('popup_video', 'Popup Video'), ('text', 'Text'), ('event', 'Event')], default='text', max_length=20),
        ),
    ]
