# Generated by Django 3.2.7 on 2021-12-06 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_auto_20211204_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
