# Generated by Django 3.2.7 on 2021-12-14 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_alter_notifications_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='template',
            field=models.CharField(choices=[('instant', 'Instant One Time'), ('event', 'Event'), ('send_coins', 'Send Coins'), ('daily', 'Daily'), ('every_14_days', 'Every 14 Days'), ('once_a_month', 'Once A Month'), ('home', 'When User Reach Home Dashboard'), ('login', 'After User Login'), ('how_to_use', 'How To Use Engage'), ('level_up_5', 'Level Up 5'), ('level_up_10', 'Level Up 10'), ('day_1_joining', 'Day 1 of Joining'), ('day_2_joining', 'Day 2 of Joining'), ('active_5_days', '5 Active Days After Joining'), ('active_10_days', '10 Active Days After Joining'), ('active_30_days', '30 Active Days After Joining'), ('dormant_3_days', 'Dormant 3 Days'), ('dormant_5_days', 'Dormant 5 Days'), ('user_register_for_tournament', 'User Registers For A Tournament'), ('user_first_tournament', 'User Who Is First In Any Tournament'), ('user_second_third_tournament', 'Users Who Win A Prize (2nd and more)'), ('user_outside_the_winning_positions', 'User Outside The Winning Positions'), ('happy_birthday', 'Happy Birthday'), ('friend_added', 'Friend Added'), ('friend_remove', 'Friend Remove'), ('friend_request', 'Friend Request'), ('video_added', 'New Video Added'), ('user_watch_video', 'If User Watches Any Video'), ('mission_completed', 'Mission Completed'), ('complete_profile', 'Complete Profile')], max_length=40, null=True),
        ),
    ]
