# Generated by Django 3.2.7 on 2021-12-23 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_alter_notifications_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameApi',
        ),
    ]
