# Generated by Django 3.2.7 on 2021-12-29 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_auto_20211229_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mission',
            old_name='free_user_coins',
            new_name='free_user_points',
        ),
        migrations.RenameField(
            model_name='mission',
            old_name='paid1_user_coins',
            new_name='paid1_user_points',
        ),
        migrations.RenameField(
            model_name='mission',
            old_name='paid2_user_coins',
            new_name='paid2_user_points',
        ),
    ]
