# Generated by Django 3.1.1 on 2022-01-14 09:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_featuredgame_nbr_of_coins'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='rules',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
