# Generated by Django 3.2.7 on 2022-01-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_auto_20220112_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredgame',
            name='nbr_of_coins',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
