# Generated by Django 3.1.1 on 2022-01-19 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_remove_game_general_rules'),
        ('core', '0073_featuredgame_nbr_of_coins'),
    ]

    operations = [
    ]
