# Generated by Django 3.1.1 on 2022-02-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_featuredgame_nbr_of_coins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_model',
            field=models.CharField(blank=True, choices=[('top_scorer', 'Top Scorer'), ('battle_royale', 'Battle Royale'), ('team_based', 'Team-Based')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='html5game',
            name='game',
            field=models.CharField(choices=[('adventure_quiz', 'Adventure Quiz'), ('angry_zombies', 'Angry Zombies'), ('alien_vs_math', 'Alien vs Math'), ('animals_memory', 'Animals Memory'), ('cannon_ball', 'Cannon Ball'), ('cat_jump', 'Cat Jump'), ('cat_vs_dog', 'Cat Vs Dog'), ('conquer_your_love', 'Conquer your love'), ('galaxy_domination', 'Galaxy Domination'), ('mad_shark', 'Mad Shark'), ('memory_animal_game', 'Memory Animal Game'), ('prehistoric_warfare', 'Prehistoric Warfare'), ('slice_fruit', 'Slice Fruit'), ('soccer_heroes', 'Soccer Heroes'), ('spot_the_difference', 'Spot the Difference'), ('super_quiz_xml', 'Super Quiz XML'), ('sweet_memory', 'Sweet Memory'), ('save_rocket', 'Save Rocket')], max_length=256),
        ),
    ]
