# Generated by Django 3.1.1 on 2022-02-28 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_auto_20220216_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='subscription',
            field=models.CharField(choices=[('free', 'Free'), ('paid1', 'Paid 1'), ('paid2', 'Paid 2')], default='free', max_length=50),
        ),
    ]
