# Generated by Django 3.1.1 on 2022-02-28 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_notifications_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_popup',
            field=models.BooleanField(default=False, verbose_name='display as popup'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='subscription',
            field=models.CharField(choices=[('free', 'Free'), ('paid1', 'Paid 1'), ('paid2', 'Paid 2'), ('all', 'All Packages')], default='all', max_length=50, verbose_name='Send to'),
        ),
    ]
