# Generated by Django 3.1.1 on 2022-03-21 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_auto_20220311_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='platform',
            field=models.CharField(choices=[('pc', 'PC'), ('mobile', 'Mobile')], default='pc', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='html5game',
            name='game',
            field=models.CharField(choices=[('adventure_quiz', 'Adventure Quiz'), ('angry_zombies', 'Angry Zombies'), ('alien_vs_math', 'Alien vs Math'), ('animals_memory', 'Animals Memory'), ('cannon_ball', 'Cannon Ball'), ('cat_jump', 'Cat Jump'), ('cat_vs_dog', 'Cat Vs Dog'), ('conquer_your_love', 'Conquer your love'), ('galaxy_domination', 'Galaxy Domination'), ('mad_shark', 'Mad Shark'), ('memory_animal_game', 'Memory Animal Game'), ('prehistoric_warfare', 'Prehistoric Warfare'), ('slice_fruit', 'Slice Fruit'), ('soccer_heroes', 'Soccer Heroes'), ('spot_the_difference', 'Spot the Difference'), ('super_quiz_xml', 'Super Quiz XML'), ('sweet_memory', 'Sweet Memory'), ('save_rocket', 'Save Rocket'), ('risky_way', 'Risky Way'), ('exit', 'Exit'), ('dots_puzzle', 'Dots Puzzle'), ('hole', 'Hole'), ('red_jumper', 'Red Jumper'), ('turkey_adventure', 'Turkey Adventure'), ('sticky_balls', 'Sticky Balls'), ('passage', 'Passage'), ('spiral_paint', 'Spiral Paint'), ('falling_numbers', 'Falling Numbers'), ('merge_numbers', 'Merge Numbers'), ('snack_circle', 'Snack and Circle'), ('triangle_way', 'Triangle Way'), ('neon_block', 'Neon Block'), ('match3_mania', 'Match3 Mania'), ('plait_puzzle', 'Plait Puzzle'), ('network', 'Network'), ('dots_and_lines', 'Dots And Lines'), ('changer_jam', 'Changer Jam'), ('proton_vs_electron', 'Proton Vs Electron'), ('color_bouncer', 'Color Bouncer'), ('tetra_block_puzzle', 'Tetra Block Puzzle'), ('garbage', 'Garbage'), ('color_lines', 'Color Lines'), ('catch_numbers', 'Catch the numbers'), ('draw_the_path', 'Draw The Path'), ('tightness', 'Tightness'), ('mirrors', 'Mirrors'), ('color_blocks', 'Color Blocks'), ('world_cargo', 'World Cargo'), ('books_tower', 'Books Tower'), ('bright_ball', 'Bright Ball'), ('dots_attack', 'Dots Attack'), ('flaying_triangle', 'Flaying Triangle'), ('pocket_jump', 'Pocket Jump'), ('go_to_dot', 'Go To Dot'), ('jump_box_hero', 'Jump Box Hero'), ('jump_red_square', 'Jump Red Square'), ('racing_game_challenge', 'Racing Game Challenge'), ('falling_dots', 'Falling Dots'), ('amazing_cube', 'Amazing Cube'), ('retro_speed2', 'Retro Speed2'), ('color_tower', 'Color Tower'), ('color_circle', 'Color Circle'), ('circle_flip', 'Circle Flip'), ('knives', 'Knives'), ('shot_pong', 'Shot Pong'), ('snake_and_circle', 'Snake and Circle')], max_length=256),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='template',
            field=models.CharField(choices=[('instant', 'Instant One Time'), ('event', 'Event'), ('send_coins', 'Send Coins'), ('daily', 'Daily'), ('every_14_days', 'Every 14 Days'), ('once_a_month', 'Once A Month'), ('home', 'When User Reach Home Dashboard'), ('login', 'After User Login'), ('how_to_use', 'How To Use Engage'), ('level_up_5', 'Level Up 5'), ('level_up_10', 'Level Up 10'), ('day_1_joining', 'Day 1 of Joining'), ('day_2_joining', 'Day 2 of Joining'), ('before_match_informative', 'Before Match Informative'), ('active_5_days', '5 Active Days After Joining'), ('active_10_days', '10 Active Days After Joining'), ('active_30_days', '30 Active Days After Joining'), ('dormant_3_days', 'Dormant 3 Days'), ('dormant_5_days', 'Dormant 5 Days'), ('user_register_for_tournament', 'User Registers For A Tournament'), ('user_first_tournament', 'User Who Is First In Any Tournament'), ('user_second_third_tournament', 'Users Who Win A Prize (2nd and more)'), ('user_outside_the_winning_positions', 'User Outside The Winning Positions'), ('happy_birthday', 'Happy Birthday'), ('friend_added', 'Friend Added'), ('friend_remove', 'Friend Remove'), ('friend_request', 'Friend Request'), ('video_added', 'New Video Added'), ('user_watch_video', 'If User Watches Any Video'), ('mission_completed', 'Mission Completed'), ('complete_profile', 'Complete Profile'), ('onward_upward', 'Onwards and Upwards')], max_length=40, null=True),
        ),
    ]
