# Generated by Django 3.1.1 on 2022-04-03 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_notificationspackage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationspackage',
            old_name='notification',
            new_name='notifications',
        ),
        migrations.AlterUniqueTogether(
            name='notificationspackage',
            unique_together={('notifications', 'package')},
        ),
    ]
