# Generated by Django 3.1.1 on 2022-04-08 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_auto_20220403_1455'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationsPackage',
        ),
    ]
