# Generated by Django 3.2.7 on 2022-08-04 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_alter_notifications_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='package',
            field=models.ManyToManyField(to='core.Package', verbose_name='Package'),
        ),
    ]
