# Generated by Django 3.2.6 on 2021-08-19 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmatch',
            name='match_id',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='match_name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='parent_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournament.tournamentmatch'),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('finished', 'Finished'), ('canceled', 'Canceled')], default='upcoming', max_length=64),
        ),
    ]
