# Generated by Django 3.2.6 on 2021-08-24 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_auto_20210819_1534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournamentmatch',
            options={'verbose_name_plural': 'Tournament Matches'},
        ),
    ]
