# Generated by Django 3.2.6 on 2021-08-24 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_alter_tournamentmatch_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='max_participants',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
