# Generated by Django 3.2.6 on 2021-08-27 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_auto_20210824_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentmatch',
            name='parent_match',
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='password',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
