# Generated by Django 3.2.6 on 2021-08-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_auto_20210827_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmatch',
            name='match_data',
            field=models.JSONField(null=True),
        ),
    ]
