# Generated by Django 3.2.6 on 2021-08-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_tournamentmatch_match_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmatch',
            name='winners',
            field=models.TextField(null=True),
        ),
    ]
