# Generated by Django 3.2.6 on 2021-08-28 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_tournamentmatch_winners'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='top_image',
            field=models.ImageField(blank=True, null=True, upload_to='tournaments/'),
        ),
    ]
