# Generated by Django 3.2.6 on 2021-09-04 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournament', '0008_tournament_top_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentinvitation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=32),
        ),
        migrations.AddField(
            model_name='tournamentinvitation',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tournament.tournament'),
        ),
        migrations.AddField(
            model_name='tournamentprize',
            name='title',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='tournamentmatch',
            name='password',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='tournamentinvitation',
            unique_together={('tournament', 'participant', 'invitee')},
        ),
    ]
