# Generated by Django 3.2.6 on 2021-09-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0010_remove_tournamentprize_coins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='image',
            field=models.ImageField(null=True, upload_to='tournaments/'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='top_image',
            field=models.ImageField(null=True, upload_to='tournaments/'),
        ),
    ]
