# Generated by Django 3.2.7 on 2021-10-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0012_tournamentparticipant_prize'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentprize',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='prizes/'),
        ),
        migrations.AddField(
            model_name='tournamentprize',
            name='prize_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('tickets', 'Tickets'), ('data', 'Data')], max_length=20, null=True),
        ),
    ]
