# Generated by Django 3.2.7 on 2021-11-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operator', '0016_remove_operatorhomesection_icon'),
        ('tournament', '0016_tournamentparticipant_is_waiting_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='is_private',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='skill_level',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='sponsors',
        ),
        migrations.RemoveField(
            model_name='tournamentmatch',
            name='status',
        ),
        migrations.AddField(
            model_name='tournament',
            name='allow_free_users',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='close_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='coins_per_participant',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='free_open_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='give_sticker',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='is_sponsored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='minimum_profile_level',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='open_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='operators',
            field=models.ManyToManyField(to='operator.Operator'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='rounds_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='inform_participants',
            field=models.PositiveIntegerField(help_text='in minutes', null=True),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='round_number',
            field=models.PositiveIntegerField(choices=[('1', '1st Round'), ('2', '2nd Round'), ('3', '3rd Round'), ('4', '4th Round'), ('5', '5th Round'), ('6', '6th Round'), ('7', '7th Round'), ('8', '8th Round'), ('9', '9th Round'), ('10', '10th Round'), ('11', '11th Round'), ('12', '12th Round'), ('13', '13th Round'), ('14', '14th Round'), ('15', '15th Round'), ('16', '16th Round'), ('17', '17th Round'), ('18', '18th Round'), ('19', '19th Round'), ('20', '20th Round')], null=True),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='tournamentmatch',
            name='winners',
            field=models.JSONField(null=True),
        ),
    ]
