# Generated by Django 3.2.7 on 2021-11-17 15:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournament', '0017_auto_20211111_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='job_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='started_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='tournamentmatch',
            name='winners',
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='winners',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
