# Generated by Django 3.2.7 on 2021-11-18 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0018_auto_20211117_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='give_sticker',
            field=models.BooleanField(default=False, verbose_name='Give stickers to participants?'),
        ),
    ]
