# Generated by Django 3.2.7 on 2021-11-27 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0020_alter_tournamentmatch_round_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentprize',
            name='prize',
            field=models.TextField(blank=True, null=True),
        ),
    ]
