# Generated by Django 3.1.1 on 2022-01-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0024_auto_20220113_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='free_open_date',
            field=models.DateTimeField(null=True, verbose_name='Public Open Date'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='open_date',
            field=models.DateTimeField(null=True, verbose_name='VIP Open Date'),
        ),
        migrations.AlterField(
            model_name='tournamentmatch',
            name='match_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='tournamentmatch',
            name='password',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='tournamentprize',
            name='prize',
            field=models.TextField(blank=True, null=True, verbose_name='Prize Description'),
        ),
    ]
