# Generated by Django 3.1.1 on 2022-01-19 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0026_auto_20220118_1613'),
        ('tournament', '0025_auto_20220114_0739'),
    ]

    operations = [
    ]
