# Generated by Django 3.1.1 on 2022-01-19 16:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0028_auto_20220119_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='minimum_profile_level',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
