# Generated by Django 3.1.1 on 2022-02-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0029_auto_20220119_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='closed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='allow_free_users',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='rounds_number',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tournamentmatch',
            name='round_number',
            field=models.IntegerField(choices=[(1, '1st Round'), (2, '2nd Round'), (3, '3rd Round'), (4, '4th Round'), (5, '5th Round'), (6, '6th Round'), (7, '7th Round'), (8, '8th Round'), (9, '9th Round'), (10, '10th Round'), (11, '11th Round'), (12, '12th Round'), (13, '13th Round'), (14, '14th Round'), (15, '15th Round'), (16, '16th Round'), (17, '17th Round'), (18, '18th Round'), (19, '19th Round'), (20, '20th Round')], null=True),
        ),
    ]
