# Generated by Django 3.1.1 on 2022-02-16 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0030_auto_20220206_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='closed_on',
        ),
    ]
