# Generated by Django 3.1.1 on 2022-02-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0031_remove_tournament_closed_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='closed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
