# Generated by Django 3.1.1 on 2022-03-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0032_tournament_closed_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='close_date',
            field=models.DateTimeField(null=True, verbose_name='Close Date(Utc)'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='end_date',
            field=models.DateTimeField(null=True, verbose_name='End Date(Utc)'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='free_open_date',
            field=models.DateTimeField(null=True, verbose_name='Public Open Date(Utc)'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='start_date',
            field=models.DateTimeField(verbose_name='Start Date(Utc)'),
        ),
        migrations.AlterField(
            model_name='tournamentmatch',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start Date(Utc)'),
        ),
    ]
