# Generated by Django 3.1.1 on 2022-03-21 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0033_auto_20220301_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='close_date',
            field=models.DateTimeField(null=True, verbose_name='Close Date'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='end_date',
            field=models.DateTimeField(null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='free_open_date',
            field=models.DateTimeField(null=True, verbose_name='Public Open Date'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='start_date',
            field=models.DateTimeField(verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='tournamentmatch',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start Date'),
        ),
    ]
