# Generated by Django 3.1.1 on 2022-04-12 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0034_auto_20220321_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='sponsored_by',
            field=models.ImageField(null=True, upload_to='tournaments/'),
        ),
    ]
