# Generated by Django 3.1.1 on 2022-04-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0035_tournament_sponsored_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='live_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='sponsored_by',
            field=models.ImageField(blank=True, null=True, upload_to='tournaments/'),
        ),
    ]
