# Generated by Django 3.1.1 on 2022-04-12 14:49

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0037_auto_20220412_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='label_next_time',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Label Next GMT Time'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='time_compared_to_gmt',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Time Compared to GMT'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='pool_prize',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
