# Generated by Django 3.2.7 on 2022-08-04 08:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournament', '0041_auto_20220516_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmatch',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participants', related_query_name='participanto', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bracket',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='close_date',
            field=models.DateTimeField(null=True, verbose_name='Close Date (in GMT)'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='end_date',
            field=models.DateTimeField(null=True, verbose_name='End Date (in GMT)'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='free_open_date',
            field=models.DateTimeField(null=True, verbose_name='Public Open Date (in GMT)'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='minimum_profile_level',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='open_date',
            field=models.DateTimeField(null=True, verbose_name='VIP Open Date (in GMT)'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='start_date',
            field=models.DateTimeField(null=True, verbose_name='Start Date (in GMT)'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='time_compared_to_gmt',
            field=models.IntegerField(default=0, verbose_name='Time compared to GMT (+ or -)'),
        ),
        migrations.AlterField(
            model_name='tournamentbracket',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tournamentinvitation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tournamentmatch',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tournamentmoderator',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tournamentparticipant',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tournamentprize',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tournamentprize',
            name='image',
            field=models.ImageField(null=True, upload_to='prizes/'),
        ),
        migrations.AlterField(
            model_name='tournamentteam',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
